# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    container_name: mysql_sas
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      # - dbdata:/var/lib/mysql
      - ./catering_init_04.sql:/docker-entrypoint-initdb.d/catering_init_04.sql

# volumes:
#   dbdata:
